### ISSUE TITLE
Which GPIO is used?

### ISSUE THREAD

**Issue by mariusvanderwerff** [AeroSteveO/ESP-Projects#1]
Hi can you explain which GPIO is used?

**Comment by AeroSteveO** [comment]
The IKEA sensor is GPIO 4 for communicating with the internal board.

 The word clock uses GPIO 2 for the connection to the addressable led strip, gpio 17 for the light sensor, and GPIO 4/5 for the RTC connection

**Comment by mariusvanderwerff** [comment]
Do you have a wire instruction for the Word clock, for now my first led of the strip is blinking blue red and green. When I open the log in ESP home some leds are on but the do fluctuate a bit, so I need to sort out what's causing it. Can I reach you by email? because I don't think it an issue
